# Generated by Django 5.0.7 on 2024-07-27 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_usercomment_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercomment',
            name='email',
        ),
    ]
